import type { Metadata } from 'next';
import { Viewport } from 'next';
import { Lobster_Two } from 'next/font/google';

import { Providers } from './providers';

import './globals.css';

const poppins = Lobster_Two({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: true
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body suppressHydrationWarning className={`${poppins.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
